apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdbv1-volume
  labels:
    type: local
spec:
  storageClassName: influxv1
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/influxdbv1"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdbv1-pv-claim
spec:
  storageClassName: influxv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
